src/main/java/edu/wustl/mir/ctt/beans/AddEventBean.java
package edu.wustl.mir.ctt.beans;

import edu.wustl.mir.ctt.Controller;
import edu.wustl.mir.ctt.log.AuditLogger;
import edu.wustl.mir.ctt.model.ECPEventTypes;
import edu.wustl.mir.ctt.model.ECPEvents;
import edu.wustl.mir.ctt.model.Event;
import edu.wustl.mir.ctt.model.StudyArmStatus;
import edu.wustl.mir.ctt.notification.NotificationException;
import edu.wustl.mir.ctt.persistence.PersistenceException;
import java.io.Serializable;
import java.util.Date;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.RequestScoped;

/**
 *
 * @author drm
 */
@ManagedBean
@RequestScoped
public class AddEventBean implements Serializable {
    private ECPEventTypes eventType;
    private Date dateOfOccurance;
    private String title;
    
    @ManagedProperty(value="#{controller}")
    private Controller controller;
    private AuditLogger logger = AuditLogger.create(AddEventBean.class);
    
    public AddEventBean() {
    }
    
    public List<ECPEventTypes> getEventTypes() {
        StudyArmStatus sas = controller.getSelectedParticipant().getStudyArmStatus();
        if(sas.equals(StudyArmStatus.CONTROL_ARM)){
            return ECPEventTypes.getControlArmUnscheduledEvents();
        } else {
            return ECPEventTypes.getUnscheduledEvents();
        }
    }

    public ECPEventTypes getEventType() {
        return eventType;
    }

    public void setEventType(ECPEventTypes eventType) {
        this.eventType = eventType;
    }
    
    public String addEventAction() throws PersistenceException, NotificationException {
        // NOTE: If the event happens to be a Change in Therapy, the Change in Therapy form does not get populated with a copy of most of the baseline therapy values
        // or the Change in Therapy until the Change in Therapy form is read (See JDBCPersistenceManager.getChangeTherapyForm for details relating to copying the Baseline
        // or Change values to the newly created Change in Therapy form).
        Event e = ECPEvents.getInstance(eventType);
        logger.audit("The addEventAction eventType is: " + eventType.getName() + "  " + eventType.name());
        e.setActualDate( dateOfOccurance);
        
        return controller.insertEventAction( e, dateOfOccurance);
    }

    public Date getDateOfOccurance() {
        return dateOfOccurance;
    }

    public void setDateOfOccurance(Date dateOfOccurance) {
        this.dateOfOccurance = dateOfOccurance;
    }
    
    public void setController(Controller c) {
        this.controller = c;
    }
    
    public Controller getController() {
        return controller;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

}

src/main/java/edu/wustl/mir/ctt/beans/BannerBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.wustl.mir.ctt.beans;

import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;
import org.apache.commons.io.IOUtils;
import edu.wustl.mir.ctt.log.AuditLogger;

/**
 *
 * @author lwalla01
 */
public class BannerBean {
    private String text;
    private String color;
    private AuditLogger logger;
    
    public BannerBean() {
        logger = AuditLogger.create(BannerBean.class);
    }
    
    public void init() {
        InputStream is = null;
        Properties bannerProperties = new Properties();
        
        try {
            is = new FileInputStream("/etc/ecp/banner.properties");
            bannerProperties.load(is);
            
            text = bannerProperties.getProperty("text");
            color = bannerProperties.getProperty("color");
        } catch (IOException ex) {
            logger.error(ex);
        } finally {
            IOUtils.closeQuietly(is);
        }
    }
    
    public String getText() {
        return text;
    }
    
    public String getColor() {
        return color;
    }
}

src/main/java/edu/wustl/mir/ctt/beans/EnrollmentBean.java
package edu.wustl.mir.ctt.beans;

import edu.wustl.mir.ctt.Controller;
import edu.wustl.mir.ctt.persistence.PersistenceException;
import edu.wustl.mir.ctt.persistence.PersistenceManager;
import edu.wustl.mir.ctt.persistence.ServiceRegistry;
import java.io.Serializable;
import java.util.Date;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.RequestScoped;

/**
 *
 * @author drm
 */
@ManagedBean
@RequestScoped
public class EnrollmentBean implements Serializable {
    private int siteId;
    private int participantId;
    private Date firstTreatmentDate;
    
    @ManagedProperty(value="#{controller}")
    private Controller controller;
    
    public EnrollmentBean() {
    }
    
    public void setController(Controller c) {
        this.controller = c;
    }
    
    public Controller getController() {
        return controller;
    }
    
    public boolean isElligible() {
        return true;
    }

    public Date getFirstTreatmentDate() {
        return firstTreatmentDate;
    }

    public void setFirstTreatmentDate(Date firstTreatmentDate) {
        this.firstTreatmentDate = firstTreatmentDate;
    }

    public int getSiteId() {
        return siteId;
    }
    
    public void setSiteId( int id) {
        siteId = id;
    }

    public int getParticipantId() {
        return participantId;
    }

    public void setParticipantId(int participantId) {
        this.participantId = participantId;
    }
    
//    public void load() throws PersistenceException {
//        if( site.getId() > 0) {
//            PersistenceManager pm = ServiceRegistry.getPersistenceManager();
//            site = pm.getSite( site.getId());
//        }
//    }
    
}

src/main/java/edu/wustl/mir/ctt/beans/StyleBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.wustl.mir.ctt.beans;

import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;
import org.apache.commons.io.IOUtils;
import edu.wustl.mir.ctt.log.AuditLogger;

/**
 *
 * @author lwalla01
 */
public class StyleBean {
    private String header;
    private AuditLogger logger;
    
    public StyleBean() {
        logger = AuditLogger.create(StyleBean.class);
    }
    
    public void init() {
        InputStream is = null;
        Properties styleProperties = new Properties();
        
        try {
            is = new FileInputStream("/etc/ecp/style.properties");
            styleProperties.load(is);
            
            header = styleProperties.getProperty("header");
        } catch (IOException ex) {
            logger.error(ex);
        } finally {
            IOUtils.closeQuietly(is);
        }
    }
    
    public String getHeader() {
        return header;
    }
}

src/main/java/edu/wustl/mir/ctt/form/CrossoverEligibilityWorkSheet.java
package edu.wustl.mir.ctt.form;

import edu.wustl.mir.ctt.model.AttributeDate;
import edu.wustl.mir.ctt.model.AttributeFloat;
import edu.wustl.mir.ctt.model.ECPFormTypes;
import edu.wustl.mir.ctt.model.PulmonaryEvaluation;
import edu.wustl.mir.ctt.model.VerificationStatus;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import edu.wustl.mir.ctt.log.AuditLogger;

public class CrossoverEligibilityWorkSheet extends BasicForm {
    
    public static final String[] SourceDocumentTypes = new String[]{"History and Physical or Consultation Note", "Operative Report of Transplant Procedure", "Pulmonary Function Test Reports (for each FEV-1 submitted)"};
    
    private String pid;
    
    public CrossoverEligibilityWorkSheet() {
        super();
        this.formType = ECPFormTypes.CROSSOVER_ELIGIBILITY_WORKSHEET;
        title = "Crossover Eligibility Work Sheet";
        this.sourceDocumentTypes = SourceDocumentTypes;
        
        AuditLogger.create(CrossoverEligibilityWorkSheet.class).debug("In constructor ()");
        
        attributes.put("date1", new AttributeDate("date1", true, false, true));
        attributes.put("date2", new AttributeDate("date2", true, false, true));
        attributes.put("date3", new AttributeDate("date3", true, false, true));
        attributes.put("date4", new AttributeDate("date4", true, false, true));
        attributes.put("date5", new AttributeDate("date5", true, false, true));
        attributes.put("date6", new AttributeDate("date6"));
        attributes.put("date7", new AttributeDate("date7"));
        attributes.put("date8", new AttributeDate("date8"));
        attributes.put("date9", new AttributeDate("date9"));
        attributes.put("date10", new AttributeDate("date10"));
        attributes.put("date11", new AttributeDate("date11"));
        attributes.put("date12", new AttributeDate("date12"));
        attributes.put("date13", new AttributeDate("date13"));
        attributes.put("date14", new AttributeDate("date14"));
        attributes.put("date15", new AttributeDate("date15"));
        attributes.put("fev11", new AttributeFloat("fev11", true, false, true));
        attributes.put("fev12", new AttributeFloat("fev12", true, false, true));
        attributes.put("fev13", new AttributeFloat("fev13", true, false, true));
        attributes.put("fev14", new AttributeFloat("fev14", true, false, true));
        attributes.put("fev15", new AttributeFloat("fev15", true, false, true));
        attributes.put("fev16", new AttributeFloat("fev16"));
        attributes.put("fev17", new AttributeFloat("fev17"));
        attributes.put("fev18", new AttributeFloat("fev18"));
        attributes.put("fev19", new AttributeFloat("fev19"));
        attributes.put("fev110", new AttributeFloat("fev110"));
        attributes.put("fev111", new AttributeFloat("fev111"));
        attributes.put("fev112", new AttributeFloat("fev112"));
        attributes.put("fev113", new AttributeFloat("fev113"));
        attributes.put("fev114", new AttributeFloat("fev114"));
        attributes.put("fev115", new AttributeFloat("fev115"));
        attributes.put("fvc1", new AttributeFloat("fvc1", true, false, true));
        attributes.put("fvc2", new AttributeFloat("fvc2", true, false, true));
        attributes.put("fvc3", new AttributeFloat("fvc3", true, false, true));
        attributes.put("fvc4", new AttributeFloat("fvc4", true, false, true));
        attributes.put("fvc5", new AttributeFloat("fvc5", true, false, true));
        attributes.put("fvc6", new AttributeFloat("fvc6"));
        attributes.put("fvc7", new AttributeFloat("fvc7"));
        attributes.put("fvc8", new AttributeFloat("fvc8"));
        attributes.put("fvc9", new AttributeFloat("fvc9"));
        attributes.put("fvc10", new AttributeFloat("fvc10"));
        attributes.put("fvc11", new AttributeFloat("fvc11"));
        attributes.put("fvc12", new AttributeFloat("fvc12"));
        attributes.put("fvc13", new AttributeFloat("fvc13"));
        attributes.put("fvc14", new AttributeFloat("fvc14"));
        attributes.put("fvc15", new AttributeFloat("fvc15"));
        
        attributes.put("slope", new AttributeFloat("slope"));
        attributes.put("significance", new AttributeFloat("significance"));
    }
	
    public CrossoverEligibilityWorkSheet( BasicForm bf) {
        super(bf);
        
        AuditLogger.create(CrossoverEligibilityWorkSheet.class).debug("In constructor (BasicForm)");
        
        this.formType = ECPFormTypes.CROSSOVER_ELIGIBILITY_WORKSHEET;
        title = bf.getTitle();
        this.sourceDocumentTypes = SourceDocumentTypes;
    }
    
    // This work sheet is normally created from values in the log.
    public CrossoverEligibilityWorkSheet( String pid, List<PulmonaryEvaluation> pulmEvals) {
        this();
        this.pid = pid;
        
        AuditLogger.create(CrossoverEligibilityWorkSheet.class).debug("Evals size " + pulmEvals.size());
        
        for (int i = 1; i < pulmEvals.size() + 1; ++i) {
            AuditLogger.create(CrossoverEligibilityWorkSheet.class).debug(pulmEvals.get(i - 1).getDate());
            attributes.get("date" + i).setValue(pulmEvals.get(i - 1).getDate());
            AuditLogger.create(CrossoverEligibilityWorkSheet.class).debug(pulmEvals.get(i - 1).getFev1());
            attributes.get("fev1" + i).setValue(pulmEvals.get(i - 1).getFev1());
            AuditLogger.create(CrossoverEligibilityWorkSheet.class).debug(pulmEvals.get(i - 1).getFvc());
            attributes.get("fvc" + i).setValue(pulmEvals.get(i - 1).getFvc());
        }
        
        AuditLogger.create(CrossoverEligibilityWorkSheet.class).debug("In constructor (pid, pulmEvals)");
        AuditLogger.create(CrossoverEligibilityWorkSheet.class).debug("Eval1: " + getDate1() + " " + getFev11() + " " + getFvc1());
        /*
        int i = 0;
        if(i < pulmEvals.size()){
            setDate1(pulmEvals.get(0).getDate());
            setFev11(pulmEvals.get(0).getFev1());
            setFvc1(pulmEvals.get(0).getFvc());
        }
        i++;
        if(i < pulmEvals.size()){
            setDate2(pulmEvals.get(1).getDate());
            setFev12(pulmEvals.get(1).getFev1());
            setFvc2(pulmEvals.get(1).getFvc());
        }
        i++;
        if(i < pulmEvals.size()){
            setDate3(pulmEvals.get(2).getDate());
            setFev13(pulmEvals.get(2).getFev1());
            setFvc3(pulmEvals.get(2).getFvc());
        }
        i++;
        if(i < pulmEvals.size()){
            setDate4(pulmEvals.get(3).getDate());
            setFev14(pulmEvals.get(3).getFev1());
            setFvc4(pulmEvals.get(3).getFvc());
        }
        i++;
        if(i < pulmEvals.size()){
            setDate5(pulmEvals.get(4).getDate());
            setFev15(pulmEvals.get(4).getFev1());
            setFvc5(pulmEvals.get(4).getFvc());
        }
        i++;
        if(i < pulmEvals.size()){
            setDate6(pulmEvals.get(5).getDate());
            setFev16(pulmEvals.get(5).getFev1());
            setFvc6(pulmEvals.get(5).getFvc());
        }
        i++;
        if(i < pulmEvals.size()){
            setDate7(pulmEvals.get(6).getDate());
            setFev17(pulmEvals.get(6).getFev1());
            setFvc7(pulmEvals.get(6).getFvc());
        }
        i++;
        if(i < pulmEvals.size()){
            setDate8(pulmEvals.get(7).getDate());
            setFev18(pulmEvals.get(7).getFev1());
            setFvc8(pulmEvals.get(7).getFvc());
        }
         i++;
       if(i < pulmEvals.size()){
            setDate9(pulmEvals.get(8).getDate());
            setFev19(pulmEvals.get(8).getFev1());
            setFvc9(pulmEvals.get(8).getFvc());
        }
        i++;
        if(i < pulmEvals.size()){
            setDate10(pulmEvals.get(9).getDate());
            setFev110(pulmEvals.get(9).getFev1());
            setFvc10(pulmEvals.get(9).getFvc());
        }
        i++;
        if(i < pulmEvals.size()){
            setDate11(pulmEvals.get(10).getDate());
            setFev111(pulmEvals.get(10).getFev1());
            setFvc11(pulmEvals.get(10).getFvc());
        }
        i++;
        if(i < pulmEvals.size()){
            setDate12(pulmEvals.get(11).getDate());
            setFev112(pulmEvals.get(11).getFev1());
            setFvc12(pulmEvals.get(11).getFvc());
        }
        i++;
        if(i < pulmEvals.size()){
            setDate13(pulmEvals.get(12).getDate());
            setFev113(pulmEvals.get(12).getFev1());
            setFvc13(pulmEvals.get(12).getFvc());
        }
        i++;
        if(i < pulmEvals.size()){
            setDate14(pulmEvals.get(13).getDate());
            setFev114(pulmEvals.get(13).getFev1());
            setFvc14(pulmEvals.get(13).getFvc());
        }
        i++;
        if(i < pulmEvals.size()){
            setDate15(pulmEvals.get(14).getDate());
            setFev115(pulmEvals.get(14).getFev1());
            setFvc15(pulmEvals.get(14).getFvc());
        }
        */
    }
    
    public String getParticipantID() {
        return pid;
    }
    
    public void setParticipantID( String id) {
        this.pid = id;
    }
    
    public Date getDate1() {
        return (Date) attributes.get("date1").getValue();
    }
    
    public void setDate1(Date date1) {
        attributes.get("date1").setValue(date1);
    }

    public VerificationStatus getDate1VerificationStatus() {
        return attributes.get("date1").getVerificationStatus();
    }
    
    public void setDate1VerificationStatus(VerificationStatus verificationStatus) {
        attributes.get("date1").setVerificationStatus(verificationStatus);
    }

    public String getDate1DccComment() {
        return (String) attributes.get("date1").getDccComment();
    }
    
    public void setDate1DccComment(String dccComment) {
        attributes.get("date1").setDccComment(dccComment);
    }

    public Date getDate2() {
        return (Date) attributes.get("date2").getValue();
    }
    

src/main/webapp/adverseEventForm.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
    
    <ui:composition template="./template/adverseEventFormTemplate.xhtml">
        <ui:define name="saeProtocolLink">
            <a href="ecpRegistryProtocol.xhtml#section6-4" target="_blank">see Protocol Section 6.4</a>
        </ui:define>
    </ui:composition>
</html>

src/main/webapp/adverseEventWorksheet.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
    
    <ui:composition template="./template/adverseEventWorksheetTemplate.xhtml">
        <ui:define name="saeProtocolLink">
            <a href="ecpRegistryProtocol.xhtml#section6-4" target="_blank">see Protocol Section 6.4</a>
        </ui:define>
    </ui:composition>
</html>

src/main/webapp/changeTherapyV8.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">

    <ui:composition template="./template/newChangeInTherapyTemplate.xhtml">
        <ui:param name="commentsQuesNum" value="7"/>
        
        <ui:define name="form_title_insert">
            
            <div id="#{controller.style.header}">
                <h3>Extracorporeal Photopheresis (ECP) for the Management of Progressive Bronchiolitis Obliterans Syndrome (BOS) in Medicare-Eligible Recipients of Lung Allografts</h3>
                <h2>CHANGE IN THERAPY - Case Report Form (CRF)</h2>
                <div>
                    <h2><center><h:outputText value="#{controller.selectedForm.title}" /></center></h2>
                </div>
            </div>
            <div>
                <p style="width: 750px; font-size: medium; color: red; font-weight: bold">
                    The medications listed in this Change in Therapy CRF are pre-populated from either the Baseline Therapy CRF or the most previous Change in Therapy CRF.  Please review all items and update the medications that have changed.
                </p>
            </div>
	    <div>
                <h2>Please include the following types of source documents:</h2>
                <div>
                <b>1. Clinic or Progress Note and/or Medication Record</b>
                </div>
            </div>
        </ui:define>
       
        <ui:define name="ecpStarted">
            <div class="treatment-parameters">
                <h:panelGrid columns="2" >
                    <h:outputLabel class="treatment-parameters-questions" value="5. Has ECP therapy been started? " />
                    <h:selectOneRadio id="quesecpstarted" class="" requiredMessage="#{msgs.ecpTreatmentStarted}" value="#{controller.changeTherapyForm.ecpTherapyStarted}" disabled="#{controller.changeTherapyForm.locked}" style="display: inline-table;">
                        <f:selectItem itemValue="true" itemLabel="YES"/>
                        <f:selectItem itemValue="false" itemLabel="NO" /> 
                        <f:selectItem itemValue="na" itemLabel="Not Applicable" /> 
                        <f:ajax execute="changeOfTherapyForm" render="@form" listener="#{controller.clearChangeTherapyDrugDosageIfNoListener}" />
                        <f:validateRequired disabled="#{!param['VALIDATE']}" />
                    </h:selectOneRadio>
                </h:panelGrid>
            </div>
            <p:message for="quesecpstarted" />
            <h:panelGroup rendered="#{controller.renderVerificationPanel('ecpTherapyStarted')}">
                <div class="selectVerificationStatusIndented">
                    <h:outputLabel value="ECP Therapy Started: VERIFICATION STATUS " rendered="true"/>
                    <h:selectOneMenu id="verifyType53" value="#{controller.changeTherapyForm.ecpTherapyStartedVerificationStatus}" rendered="true">
                        <f:selectItems value="#{controller.changeTherapyForm.verificationTypes}" var="v" itemValue="#{v}" itemLabel="#{v.name}"/>
                    </h:selectOneMenu>
                </div>
                <div class="selectVerificationStatusIndented">
                    <h:outputText value="DCC Query Comment: " rendered="true" />
                    <h:inputTextarea value="#{controller.changeTherapyForm.ecpTherapyStartedDccComment}" rows="1" cols="50" rendered="true" /> 
                </div>
            </h:panelGroup>
           <div class="change-therapy-ques4-indent">
                <b>If no, give reason why ECP therapy was not started: </b>
                <h:inputTextarea id="quesecpnotstartedreason" value="#{controller.changeTherapyForm.ecpTherapyNotStartedReason}" rows="2" cols="80" disabled="#{controller.changeTherapyForm.locked || controller.changeTherapyForm.ecpTherapyStarted == true}" />
            </div>
            <h:panelGroup rendered="#{controller.renderVerificationPanel('ecpTherapyNotStartedReason')}">
                <div class="selectVerificationStatusIndented">
                    <h:outputLabel value="ECP Therapy Started Reason: VERIFICATION STATUS " rendered="true"/>
                    <h:selectOneMenu id="verifyType55" value="#{controller.changeTherapyForm.ecpTherapyNotStartedReasonVerificationStatus}" rendered="true">
                        <f:selectItems value="#{controller.changeTherapyForm.verificationTypes}" var="v" itemValue="#{v}" itemLabel="#{v.name}"/>
                    </h:selectOneMenu>
                </div>
                <div class="selectVerificationStatusIndented">
                    <h:outputText value="DCC Query Comment: " rendered="true" />
                    <h:inputTextarea value="#{controller.changeTherapyForm.ecpTherapyNotStartedReasonDccComment}" rows="1" cols="50" rendered="true" /> 
                </div>
            </h:panelGroup>
        </ui:define>
        
        <ui:define name="ecpDiscontinued">
            <h:outputLabel class="treatment-parameters-questions" value="6. Has ECP therapy been placed on hold, postponed, or discontinued? " />
        </ui:define>
        
        <ui:define name="ecpDiscontinuedDate">
            <b>a. If yes, date placed on hold, postponed, or discontinued: </b>
        </ui:define>
        
        <ui:define name="ecpDiscontinuedReason">
            <b>b. If yes, reason for hold, postponement, or discontinuation: </b>
        </ui:define>
    </ui:composition>

</html>

src/main/webapp/studyArmEligibilitySuccess.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">
    
    <ui:composition template="/template/template.xhtml">
        <ui:define name="body">
            
            <h:panelGrid rendered="#{calcController.eligibilityScreeningPassed}">
                <h1 style="color:red; font-size:24px;">Enrollment Determination Results</h1>
                <h2>This patient is now ENROLLED in the RCT Study.</h2>

                <h:panelGrid rendered="#{calcController.declineScreeningPassed}">
                    <h2>The participant identification number is ${calcController.participantID}.</h2>

                    <p style="width: 850px; font-size: large; color: red; font-weight: bold">
                        Treatment assignment will not be revealed until the Baseline Quality of Life questionnaire is confirmed.
					</p>
                    <p style="width: 850px; font-size: large; color: red; font-weight: bold">
                        Please make a NOTE of the participant identification number ${calcController.participantID}.
                        The participant identification number should be recorded on all communication with
                        the Washington University Academic Research Organization (ARO) concerning this participant.
                    </p>
                    <p style="width: 850px; font-size: large; color: red; font-weight: bold">
                        <u>Important and Time-Sensitive:</u> Please PRINT this subject's Confirmation of Eligibility (COE) Form and have
                        an authorized physician investigator sign and date the COE form. Scan and upload the signed COE form along with 
                        the de-identified Source Documents listed at the top of the COE Form.  Per <a href="ecpRegistryProtocol.xhtml#section3-7" target="_blank">Protocol Section 3.7</a>, submission of this signed 
                        COE Form with DCC Verification is required before ECP or any study-related invasive procedure (e.g. central venous catheter placement) may be performed.
                    </p>
                    <h:form >
                        <h:commandButton value="Click to ADVANCE to the COE Form to print and confirm QOL" action="#{controller.registryLoginAction()}" />
                    </h:form>

                </h:panelGrid>
<!--
                <h:form >
                    <h:panelGrid columns="2">
                        <h:commandButton value="Enroll Patient..." action="# {calcController.enrollParticipantIntoECPStudyAction}" />
                        <h:commandButton value="Cancel" action="# {calcController.cancelCalculationAction()}" />
                    </h:panelGrid>
                </h:form>
 -->
            </h:panelGrid>
            
            
            


            <h:panelGrid  rendered="#{calcController.eligibilityScreeningFailed}">
                <h1 style="color:red; font-size:24px;">Enrollment Determination Results</h1>
                <h2>This patient is NOT eligible for enrolling into the study currently,</h2>
                <h2>based on their answers to the inclusion and exclusion criteria.</h2>
                <p>
<!--                    Eligibility failed on the following criterion:  -->
<!--                    <h:outputText value="# {calcController.rule}"/>  -->
                </p>
                <p>
<!--                    <h:outputText value="index = # {calcController.notEnrollmentEligible} "/>  -->
                </p>
                <h:form >
                    <h:panelGrid columns="2">
                        <h:commandButton value="Cancel" action="#{calcController.cancelCalculationAction()}" />
                    </h:panelGrid>
                </h:form>
            </h:panelGrid>
            

        </ui:define>
    </ui:composition>
    
</html>